<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Fabiq.SmartFactory.AnomalyWorker-42d37930-8503-4360-b22a-e1efc204c2b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.16" />
  </ItemGroup>
</Project>
